language: go
go:
 - 1.4
install:
 - true
before_script:
 - go get golang.org/x/tools/cmd/vet
 - go get github.com/kr/godep
 - wget http://s3.amazonaws.com/influxdb/influxdb_latest_amd64.deb
 - sudo dpkg -i influxdb_latest_amd64.deb
 - sudo service influxdb start
script:
 - export PATH=$PATH:$HOME/gopath/bin
 - ./deploy/check_gofmt.sh .
 - ./hooks/check_boilerplate.sh
 - go vet github.com/newrelic-forks/cadvisor/...
 - godep go test -v -race -test.short github.com/newrelic-forks/cadvisor/...
 - godep go build github.com/newrelic-forks/cadvisor
